# <<< common setting >>>

# deploy mode <"static", "runtime", "fcgi-*"> (required)
type: "static"

# script executed on startup (default: null)
startup: null

# use external databases (default: false)
use_mongodb: false
use_mariadb: false

# relative path to document root (default: .)
work_dir: "."

# <<< runtime only setting >>>

# docker entrypoint command (default: "cat")
entrypoint: "cat"

# which port to proxy via http(80) (default: null)
http_proxy: null

# which port to expose <array or int> (default: [])
expose: []

# enviromnent variables passed to docker container (default: {})
envs: {}

# <<< static or http-proxied-runtime only setting >>>

# additional server name <array or string> (default: [])
cname: []

# parse user token, restrict access from non-traP user <"off", "soft", "hard"> (default: "off")
internal: "off"

# use secure access <"off", "soft", "hard"> (default: "off")
https: "off"

# <<< branch deploy setting >>>

# custom deploy setting <see document!> (default: {master: null})
branch:
  master: null
