# deploy mode <"static", "runtime"> (required)
type: "static"

# additional server name <array or string> (default: [])
cname: []

# script executed on startup (default: null)
startup: null

# use external databases (default: false)
use_mongodb: false
use_mariadb: false

# relative path to document root (default: .)
work_dir: "."

# [runtime] docker image to use (default: "kazsw/arch")
image: "kazsw/arch"

# [runtime] docker entrypoint command (default: "")
entrypoint: ""

# [runtime] which port to proxy via http(80) (default: null)
http_proxy: null

# [runtime] which port to expose (default: null)
expose: null

# [runtime] enviromnent variables passed to docker container (default: {})
envs: {}

# custom deploy setting <see document!> (default: {master: null})
branch:
  master: null
